### ISSUE TITLE
[OZ][N-07]:BIT Token Address Is Used Instead of MNT Token Address

### ISSUE THREAD

**Issue by Ethanncnm** [mantlenetworkio/mantle#1037]
**Describe the bug**
The bridge contracts have specific logic to handle MNT tokens but the L1StandardBridge
contract currently associates the BIT token with the L2 Mantle token. Consider reusing the 
existing variable to identify the MNT token address.
Note that the L2 token also still references the BIT token and should be updated accordingly.

**Comment by Tri-stone** [comment]
Yes, after our official Mantle token deployed on Ethereum, we will change it from `BIT` to `MNT`.
