### ISSUE TITLE
[OZ][N-11]: Use of Hardcoded Values

### ISSUE THREAD

**Issue by Ethanncnm** [mantlenetworkio/mantle#1039]
**Describe the bug**
The L1StandardBridge contract has the address of the MNT token hardcoded. Consider
creating a constant variable and using it instead of the hardcoded address for clarity and
readability.
Similarly, the L2StandardBridge contract hardcodes the IL2StandardERC20 identifier.
Consider using the more expressive type(IL2StandardERC20).interfaceId statement
instead.

**Comment by Tri-stone** [comment]
We think it's fine to hardcode it.
Moreover, how does the address come from and the purpose is clearly explained in the code comments.
