### ISSUE TITLE
[CS][5.16]: TssStakingSlashing - deposit.pledgor Can Be Removed Minor

### ISSUE THREAD

**Issue by Ethanncnm** [mantlenetworkio/mantle#1068]
**Describe the bug**
The staking() method enforces that msg.sender == pubkeyToAddress(pubKey) on the first deposit. On every further deposit, it is checked that the provided pubKey matches the stored one for the msg.sender. This means that only the owner of the pubKey can stake on their key. Hence, there is no need for storing the pledgor with the deposit structure.

**Expected behavior**
Remove the pledgor variable. Consider refactoring the method and simplifying it as much as possible, as it is somewhat convoluted now. There are opportunities to remove certain checks. It might be considered to open up staking to any msg.sender and crediting it to the address reconstructed for the pubkey instead. The initial for loop can be removed by consistently enforcing sane slashing params.

**Comment by byteflyfunny** [comment]
The adjustment of the related smart contract logic is significant, and the issue no longer exists.
