### ISSUE TITLE
[CS][5.18]: Use .call() Instead of .transfer() in Payment Functions 

### ISSUE THREAD

**Issue by Ethanncnm** [mantlenetworkio/mantle#1070]
**Describe the bug**
Currently, all payment functions in the contract use transfer to send ETH to a recipient address. While this is a working way to transfer ETH, transfer limits the amount of gas that can be used in the execution of the recipient function to 2300 gas. This can be insufficient for functions that require more gas to execute and can result in a transaction failing with an out-of-gas error.

People used to recommend using the transfer function instead of call to prevent reentrancy attacks (because of its fixed gas amount). However, the gas costs of the EVM are regularly subject to changes which might make reentrancy attacks possible even when using transfer. Thus, giving a false sense of security.

Because of these issues, the transfer method might be removed in the next major Solidity release. This is one more argument to stop using transfer.

**Expected behavior**
To avoid these limitations and make sure that the code is future-proof, we recommend using call instead of transfer in all payment functions. call does not enforce a constant gas value for the external call and returns a boolean value indicating whether the call executed successfully or not. One should make sure to check the value returned by call and use proper reentrancy guards if they are needed.

**Comment by aodhgan** [comment]
This can be closed - acknowledging the only remaining places `.transfer(ETHER_VALUE)` is used is in mantleWETH which is a direct fork of canonical WETH9 (https://github.com/gnosis/canonical-weth/blob/master/contracts/WETH9.sol) and `.transfer()` is widely accepted to be acceptable there. 
`.transfer()` is also used in scripts and tests, but not deployable contract code.
