### ISSUE TITLE
Load balancer solution for Mantle RPC service

### ISSUE THREAD

**Issue by FletcherMan** [mantlenetworkio/mantle#203]

**Comment by FletcherMan** [comment]
[Proxyd config example](https://c1ey4wdv9g.larksuite.com/docx/doxus3m6pgFVvz3XofUIkGp5iCh)

**Comment by shidaxi** [comment]
* cache `eth_chainId` `eth_getbalanceByNumber` and so on
* rate limit

**Comment by shidaxi** [comment]
done
