### ISSUE TITLE
Bug in TssGroupManager

### ISSUE THREAD

**Issue by byteflyfunny** [mantlenetworkio/mantle#238]
The whole network is running in local model with mantle-local-network project.
The problem occurs when tss nodes send transactions to set group public key.
I have debug the contract code ,and found the bug focus on the "activeTssMembers.push(inActiveTssMembers[i]);" in the updateTssMember function.
There is some wrong when push bytes into arrays.But I haven't get the reason.

**Comment by byteflyfunny** [comment]
the reason is out of gas. The function which updateTssMember is too expensive

**Comment by guoshijiang** [comment]
issure rebuild: https://github.com/mantlenetworkio/mantle/issues/453
