### ISSUE TITLE
For query, also check whether there is balance to pay the gas fee

### ISSUE THREAD

**Issue by songyaoshun** [mantlenetworkio/mantle#294]
when the wallet have not l2 BIT and to query L2_BIT_ETH_TOKEN.totalSupply/L2_BIT_ETH_TOKEN.balanceOf, requst errors: 
{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"insufficient balance to pay for gas\"}}

code:
![image](https://user-images.githubusercontent.com/12236588/202642845-27b56eb7-c915-462e-b3c8-95389ada5637.png)

error messages:
![image](https://user-images.githubusercontent.com/12236588/202642966-8cb70602-b411-403a-9756-1a6ff45188e3.png)

**Comment by songyaoshun** [comment]
the localnetwork have not this bug, The possible reasons are testnet l2 ETH contract is different of localnetwork's contract

**Comment by wukongcheng** [comment]
https://github.com/mantlenetworkio/mantle/pull/317

**Comment by wukongcheng** [comment]
duplicate with https://github.com/mantlenetworkio/mantle/issues/321
