### ISSUE TITLE
Mantle monitoring dashboard

### ISSUE THREAD

**Issue by HarryWong99** [mantlenetworkio/mantle#310]

**Comment by shidaxi** [comment]
https://grafana.davionlabs.com/d/KDpICfOVk/mantle-dashboard?orgId=1

<img width="529" alt="image" src="https://user-images.githubusercontent.com/3312375/203931832-31d7dd2a-7b82-4f4d-9ecc-ae8f29fcba74.png">

**Comment by shidaxi** [comment]
done. closed.
