### ISSUE TITLE
fix the project 'mantle-token-lists'

### ISSUE THREAD

**Issue by HarryWong99** [mantlenetworkio/mantle#319]
https://github.com/mantlenetworkio/mantle-token-lists#adding-a-token-to-the-list

**Comment by HarryWong99** [comment]
1. delete optimism related description
2. link is incorrect



![Image](https://user-images.githubusercontent.com/34086765/203248599-b41aec6e-02fd-4728-805b-232d3363c189.png)

**Comment by bradyjoestar** [comment]
closed for https://github.com/mantlenetworkio/mantle-token-lists
