### ISSUE TITLE
Fix The contract query interface checks if the user has enough money to pay the GasFee

### ISSUE THREAD

**Issue by curryxbo** [mantlenetworkio/mantle#321]
1. [x] Adjust the GasPrice of the system to a non-zero value

2. [x] Add the switch of whether to charge L2GasFee. After calculating L1Fee, whether to reset the user's GasPrcie to 0 according to the switch selection of whether to charge fee

**Comment by wukongcheng** [comment]
duplicate with https://github.com/mantlenetworkio/mantle/issues/294
