### ISSUE TITLE
Sequencer: Implement L2 rollback

### ISSUE THREAD

**Issue by curryxbo** [mantlenetworkio/mantle#360]
- [x] https://github.com/mantlenetworkio/mantle/issues/386
- [x] https://github.com/mantlenetworkio/mantle/issues/387
- [x] https://github.com/mantlenetworkio/mantle/issues/388
- [x] https://github.com/mantlenetworkio/mantle/issues/389

**Comment by Kukoomomo** [comment]
Implement the FraudProofReorgRequest service. When receiving a reorg request with a tss signature, construct a FraudProofReorgMsg and broadcast it #336

**Comment by Kukoomomo** [comment]
Implement the FraudProofReorgRequest service. When receiving a reorg request with a tss signature, construct a FraudProofReorgMsg and broadcast it #351
