### ISSUE TITLE
Sequencer: Sequencer Reorg drops blocks that are not  accept by Scheduler

### ISSUE THREAD

**Issue by curryxbo** [mantlenetworkio/mantle#391]
Under the condition that everything is normal on the network, Sequencer will follow the inherent switching process to issue blocks in turn according to Scheduler's scheduling. However, when Sequencer and Scheduler are disconnected, the Scheduler will reclaim the right of the current Sequencer to produce blocks. But Sequencer doesn't know that, so it continues to produce block, and when the network connection is up, this node should Reorg Invalid block

**Comment by Kukoomomo** [comment]
Only scheduler produce blocks so we do not need the reorg method
