### ISSUE TITLE
Tss enhancement implementation plan

### ISSUE THREAD

**Issue by FletcherMan** [mantlenetworkio/mantle#4]
Related sub issues:
https://github.com/bitnetworkio/bitnetwork/issues/9
https://github.com/bitnetworkio/bitnetwork/issues/35
https://github.com/bitnetworkio/bitnetwork/issues/36

**Comment by FletcherMan** [comment]
**Support full node(block sync) - qingrui.shen**
Full node needs to be supported for state transition

**Tss manager - fletcher.fan**
Websocket Server 
Request Acceptor
Accpet the request for signing
- tx batches need to be submitted to DA
- state batches(execution results) need to be submitted to Layer1
from batch submitter
Signing Task Controller
- Get the requests to be handled
- Confirm the tss members what will join the signing task corresponding to the event via communicating with each tss node
- Retrieve the signature by dispatching the signing task to tss members
Govern
- Tssnode liveness management
- Collect the malicious behaviors of tss nodes, and build the the transaction to submit the slashing tx to Layer1

**Tss node - jay.liu**
Websocket client
Tss Core
p2p communication
tss algorithm
Request Validation

**Batch submitter - Shijiang.Guo**
Ask tss manger to generate the signature for tx batches and state batches. 

**L2geth - Shijiang.Guo Corey.zhang**
Fees calculation 
Record fees with block ID in TssRewardContract after each block

**Contacts**
- Tss nodes selection - Shijiang Guo, kuk oo
  - Tss staking contract
    - Stake bit for selection
    - Tss members confirm
    - Tss CPK confirm

- Incentive - qingrui.shen fletcher.fan
  - TssRewardContract(L2): 
    - record tss nodes reward for each block
    - claim reward for tss nodes
  -  provide entrance for initiating L2ClaimTssReward message(claim reward payload on L2), and calling sendCrossDomainMessage
  - SCC adjustment

- Slashing - Shijiang Guo, kuk oo
Contract(L1) for recording malicious behavior of tss nodes, and slashing stakes for the malicious tss node.

**Comment by byteflyfunny** [comment]
Related sub issue about tss node:
#10
