### ISSUE TITLE
batch submitter submit rollback information to contract and report error

### ISSUE THREAD

**Issue by tw5428561** [mantlenetworkio/mantle#400]
**System Specs:**
 - OS: mac
 - Blockscout Version/branch: efd3a29e07589bfe5586acd9cd9c07295b8c5b9d

**Describe the bug** 
batch-submitter submit rollback information to contract and report error.

**To Reproduce** 
1. tssmanager return rollback information 
2. batch-submitter submit rollback information
3. error

**Expected behavior** 
batch submitter submitted success

**Screenshots** 
![image](https://user-images.githubusercontent.com/104289084/206437099-bb3efe34-f925-4089-b43f-28b076f2f9a6.png)

**Comment by byteflyfunny** [comment]
test cases cause such errors.
tss and batch submitter optimized code for this scenes
