### ISSUE TITLE
rollup l2 transfer data submitted to eigenDA error

### ISSUE THREAD

**Issue by tw5428561** [mantlenetworkio/mantle#425]
**System Specs:**
 - OS: mac
 - Mantle Version/branch: d0faf18cca0a3a25a138e45614a4e1581f83b8a0

**Describe the bug** 
rollup l2 transfer data submitted to eigenDA error

**To Reproduce** 
1. l1 deposit bit l2
2. l2 transfer
3. See erro

**Expected behavior** 
Proper submission to eigenDA

**Screenshots** 
![image](https://user-images.githubusercontent.com/104289084/207276699-b76a3801-2ee9-469f-b6b3-235c730646c0.png)
![image](https://user-images.githubusercontent.com/104289084/207276900-37f74ef8-5451-4290-acf9-3a49b6df6d2e.png)

**Comment by guoshijiang** [comment]
pr: https://github.com/mantlenetworkio/mantle/pull/433
