### ISSUE TITLE
When trying to integrate the sequencer feature with mantle, sending transactions directly to the sequencer node will throw "cannot send raw transaction while syncing"

### ISSUE THREAD

**Issue by bradyjoestar** [mantlenetworkio/mantle#449]
As the title says.

Reproduce：
- https://github.com/mantlenetworkio/mantle/tree/wb/seq-intergrating-main
- https://github.com/mantlenetworkio/mantle-test/tree/wb/debug-sequencer

**Comment by HaoyangLiu** [comment]
closed by https://github.com/mantlenetworkio/mantle/pull/434
