### ISSUE TITLE
Minor licensing issue

### ISSUE THREAD

**Issue by smartcontracts** [mantlenetworkio/mantle#566]
Hi! I work on Optimism over at OP Labs. We're excited to see that Mantle is building on top of the OP Stack! We wanted to quickly point out that the MIT license requires maintaining the original copyright notice ("Copyright Optimism") but that you are more than welcome to add your own copyright below this ("Copyright Mantle"). It seems that the original copyright notice [was replaced](https://github.com/mantlenetworkio/mantle/blob/a94a92e29c5bd0b2f80ec6ac490849708c85200a/LICENSE#L3). Not a big deal, just making aware if not already.

**Comment by bradyjoestar** [comment]
Changed. Thank you for your reminder, and thank you for your team's contribution to this industry.
