### ISSUE TITLE
FraudProof: remove lastResolvedAssertionID

### ISSUE THREAD

**Issue by silmaj** [mantlenetworkio/mantle#690]
redundant public variable that describe latestAssertion staker created 
        lastResolvedAssertionID++;
        lastConfirmedAssertionID = lastResolvedAssertionID;

**Comment by Kukoomomo** [comment]
In the normal logic of the code,`lastResolvedAssertionID` is the same as `lastConfirmedAssertionID`, but in the `rejectFirstUnresolvedAssertion` method, only `lastResolvedAssertionID` is changed, but `lastConfirmedAssertionID` is not changed. It is recommended not to remove `lastResolvedAssertionID` if we are not familiar with the necessity of this
