### ISSUE TITLE
[Module]: modulize the setcode of l2geth

### ISSUE THREAD

**Issue by bradyjoestar** [mantlenetworkio/mantle#855]
we currently create a simply upgrade function for any further upgrade.
When we have the completely governance , we could wrap all upgrade into a special upgrade-transaction, and specify a custom address of `to`, i.e : 0x420000000000000000000000000000000000001F

at present , we choose this simple way.

**Comment by agnarsong** [comment]
This Issues has already been validated. Details can be found in the test record.

https://uponly.larksuite.com/docx/Pg9ydUSNkobsrRxx22wu9yhwsop
